-- "서울"에 위치한 식당
-- 문자열 비교 : LIKE, 임의의 문자열 : %
-- 식당별 평균 점수 : GROUP BY
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE),2) as REVIEW_SCORE
FROM REST_INFO AS I
JOIN REST_REVIEW AS R ON I.REST_ID = R.REST_ID
WHERE I.ADDRESS LIKE "서울%"
GROUP BY I.REST_ID
ORDER BY REVIEW_SCORE DESC, I.FAVORITES DESC