-- 단순 END_DATE - START_DATE 를 하면 원하는 날짜 차이가 나오지 않는다. 
-- 그래서 두 기간 사이의 일수 계산을 계산해주는 DATEDIFF() 함수를 사용한다. 
-- DATEDIFF(END_DATE, START_DATE) 결과는 0이다. 
-- 하지만 문제에서 대여기간 계산은 오늘 빌려서 오늘 반납은 대여기간을 1로 계산한다 : DATEDIFF + 1 
SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE)+1),1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
GROUP BY CAR_ID
HAVING AVG(DATEDIFF(END_DATE, START_DATE)+1) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC