-- 재귀 쿼리
WITH RECURSIVE TMP AS (
    -- Non-Recursive 문장( 첫번째 루프에서만 실행됨 )
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
                       
    UNION ALL

    -- Recursive 문장
    SELECT E.ID, E.PARENT_ID, GEN+1 AS GEN
    FROM TMP T
    JOIN ECOLI_DATA E ON T.ID = E.PARENT_ID)

SELECT COUNT(*) AS COUNT, GEN AS GENERATION
FROM TMP
WHERE ID NOT IN (SELECT DISTINCT PARENT_ID FROM TMP WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION ASC