#SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(P.PRICE * O.AMOUNT) AS TOTAL_SALES
#FROM FOOD_PRODUCT P
#JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
#WHERE YEAR(O.PRODUCE_DATE) = 2022 && MONTH(O.PRODUCE_DATE) = 5
#GROUP BY P.PRODUCT_ID
#ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC












select O.PRODUCT_ID, P.PRODUCT_NAME, (sum(P.PRICE * O.AMOUNT)) as TOTAL_SALES
from FOOD_ORDER O
join FOOD_PRODUCT P on O.PRODUCT_ID = P.PRODUCT_ID
where date_format(O.PRODUCE_DATE, '%Y-%m') = '2022-05'
group by O.PRODUCT_ID
order by TOTAL_SALES desc, O.PRODUCT_ID asc