#SELECT F.FLAVOR
#FROM FIRST_HALF F
#JOIN JULY J ON F.FLAVOR = J.FLAVOR
#GROUP BY F.FLAVOR
#ORDER BY SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) DESC
#LIMIT 3;



select J.FLAVOR
from JULY J
group by J.FLAVOR
order by (sum(J.TOTAL_ORDER) + (select F.TOTAL_ORDER from FIRST_HALF F where J.FLAVOR = F.FLAVOR)) desc
limit 3