-- 주의할 점
-- 날짜 형식 변환 : DATE_FORMAT
-- "여성" 회원
-- 달 비교 : MONTH()
-- IS NULL / IS NOT NULL
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, "%Y-%m-%d") as DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE MONTH(DATE_OF_BIRTH) = 3 AND GENDER = "W" AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC