-- 코드를 작성해주세요
SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR, (E2.MAX_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV, E.ID
FROM ECOLI_DATA E
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
     FROM ECOLI_DATA
     GROUP BY YEAR(DIFFERENTIATION_DATE)) E2 ON YEAR(E.DIFFERENTIATION_DATE) = E2.YEAR
GROUP BY YEAR(E.DIFFERENTIATION_DATE), E.SIZE_OF_COLONY, E.ID, E2.MAX_SIZE
ORDER BY YEAR, YEAR_DEV