-- 코드를 작성해주세요
SELECT I.ID AS ID, N.FISH_NAME AS FISH_NAME, I.LENGTH AS LENGTH
FROM FISH_INFO I
JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
WHERE (I.FISH_TYPE, I.LENGTH) IN (SELECT FISH_TYPE, MAX(LENGTH) 
                                  FROM FISH_INFO 
                                  GROUP BY FISH_TYPE)
GROUP BY I.FISH_TYPE, I.ID, I.LENGTH, N.FISH_NAME
ORDER BY ID